BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 10
  LR: 1e-4
  MODEL_FILE_NAME: vv100_vv100_UBFC-rPPG_physformer_small_FI56
  PLOT_LOSSES_AND_LR: True
  DATA:
    INFO:
      GENDER: [1,2]  # M-1; F-1
      FITZPATRICK: [5,6]
      LOCATION: [1,2,3,4,5,6,7,8,9,0]  #  'KLL'-1; 'KU'-2; 'B'-3; 'T'-4; 'KUL'-5; 'WZC'-6; 'A'-7; 'TB'-8; 'RT'-9; 'KL'-0
      FACIAL_MOVEMENT: [1,2,3]  #  'No movement'-1; 'Moderate movement'-2; 'Slight movement'-3
      TALKING: [1,2]  # 'N'-1; 'Y'-2
    FS: 30
    DATASET: vv100
    DO_PREPROCESS: False    # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data1/VitalVideo/vv100"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/data1/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"   # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "/data1/lxy/rPPG-Toolbox-main/vv100_FI56_physformer.csv"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
VALID:
  DATA:
    INFO:
      GENDER: [1,2]  # M-1; F-1
      FITZPATRICK: [1,2,3,4,5,6]
      LOCATION: [1,2,3,4,5,6,7,8,9,0]  #  'KLL'-1; 'KU'-2; 'B'-3; 'T'-4; 'KUL'-5; 'WZC'-6; 'A'-7; 'TB'-8; 'RT'-9; 'KL'-0
      FACIAL_MOVEMENT: [1,2,3]  #  'No movement'-1; 'Moderate movement'-2; 'Slight movement'-3
      TALKING: [1,2]  # 'N'-1; 'Y'-2
    FS: 30
    DATASET: vv100
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data1/VitalVideo/vv100"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/data1/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"   # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data1/gscratch/ubicomp/xliu0/data3/mnt/Datasets/UBFC-rPPG/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/data1/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"      # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.1
  NAME: PhysFormer_small
  PHYSFORMER:                     # Probably need to update these in some meaningful way
    PATCH_SIZE: 4
    DIM: 96
    FF_DIM: 144
    NUM_HEADS: 4
    NUM_LAYERS: 4
    THETA: 0.7
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30        # In seconds
  MODEL_PATH:   ""